# TruthLens AI
## Notebook 1: Data Loading

### Objectives
- Load Fake and Real news datasets
- Understand dataset structure
- Explore columns
- Check missing values
- Merge datasets
- Save processed dataset

In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
import sys
print(sys.executable)

C:\Users\vijay\OneDrive\Desktop\TruthLens-AI\venv\Scripts\python.exe

In [4]:
fake_df = pd.read_csv("../data/Fake.csv")
true_df = pd.read_csv("../data/True.csv")

print("Datasets loaded successfully!")

Datasets loaded successfully!

In [5]:
fake_df = pd.read_csv("../data/Fake.csv")

In [6]:
print("Fake News Dataset Shape:", fake_df.shape)
print("Real News Dataset Shape:", true_df.shape)

Fake News Dataset Shape: (23481, 4)
Real News Dataset Shape: (21417, 4)

In [7]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [9]:
print(fake_df.columns)
print(true_df.columns)

Index(['title', 'text', 'subject', 'date'], dtype='str')
Index(['title', 'text', 'subject', 'date'], dtype='str')

In [10]:
fake_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  str
 1   text     23481 non-null  str
 2   subject  23481 non-null  str
 3   date     23481 non-null  str
dtypes: str(4)
memory usage: 60.4 MB

In [11]:
true_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  str
 1   text     21417 non-null  str
 2   subject  21417 non-null  str
 3   date     21417 non-null  str
dtypes: str(4)
memory usage: 51.6 MB

In [12]:
fake_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [13]:
true_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [14]:
fake_df["label"] = 0   # Fake News
true_df["label"] = 1   # Real News

In [15]:
news_df = pd.concat([fake_df, true_df], ignore_index=True)

In [16]:
news_df = news_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [17]:
news_df.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [18]:
news_df.shape

(44898, 5)

In [19]:
news_df.to_csv("../data/news_dataset.csv", index=False)

print("Merged dataset saved successfully!")

Merged dataset saved successfully!

In [20]:
print(news_df["subject"].value_counts())

subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64